import "./globals.css";
import Header from "./component/header/header";
import ThemeProvider from "./component/themeprovider/ThemeProvider";
import Footer from "./component/footer/Footer";
import Modal from "./component/modal/Modal";
import ModalParent from "./component/modal/ModalParent";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`flex flex-col min-h-screen `}>
        <ThemeProvider>
          <Header />
          {children}
          <ModalParent />
          <Modal />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
